alias .....="cd ../../../.."
alias ....="cd ../../.."
alias ...="cd ../.."
alias ..="cd .."
alias chad="NVIM_APPNAME=nvchad nvim"
alias grep="grep --color=auto"
alias ll="ls -la --color=auto"
alias ls="ls -a --color=auto"
alias vim="nvim"
